# Generated by Django 5.1.6 on 2025-02-26 11:38

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pusher_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='app_secret_token',
            field=models.CharField(default=secrets.token_hex, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='headers',
            field=models.JSONField(default=dict),
        ),
    ]
